name: Terraform Apply (infra only)

on:
  workflow_dispatch: {}   # يدوي فقط

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform   # نشتغل داخل مجلد terraform فقط

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out plan.out

      - name: Terraform Apply (auto approve)
        run: terraform apply -auto-approve plan.out

      - name: Export outputs to JSON
        run: terraform output -json > tf-outputs.json

      - name: Show key outputs in summary
        run: |
          echo "### Terraform Outputs" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          terraform output >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload outputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-outputs
          path: terraform/tf-outputs.json
